In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.1.0'

In [5]:
pwd()

'/home/gonzalopc/Documentos/programas_mios/TFM_AFI_2025/TFM_AFI_2025/AAA_code'

## 1. Carga de ficheros
Y primera inspección de los mismos

In [7]:
# 1. Cargar ficheros de CBP_drug_seizures
files = '../CBP_drug_seizures/amo-drug-seizures-fy22-fy25-nov.csv' # Generar mascara para obtener todos los csv de la carpeta
drug_seizure_DF = pd.read_csv(files,sep=',') # header = infer

In [8]:
drug_seizure_DF

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
0,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,AMOC Air And Marine Operations Center,Cocaine,1,1539.69
1,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,Ground Tactical Air Controller,Fentanyl,2,60.63
2,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Cocaine,1,5805.77
3,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Houston,Marijuana,1,9415.35
4,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Jacksonville,Cocaine,1,2657.03
...,...,...,...,...,...,...,...,...,...
1293,2023,SEP,Air and Marine Operations,Southwest Border,Land,NASOC - San Angelo,Cocaine,1,0.13
1294,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Cocaine,1,14.37
1295,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Fentanyl,1,2.45
1296,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Methamphetamine,1,5.73
1297,2023,SEP,Air and Marine Operations,Southwest Border,Other,San Diego Air And Marine Branch,Fentanyl,2,0.33

FY: hace referencia a 'Fiscal Year' que en USA empiza a contar el 1 de octubre del año "anterior". Es decir, October 2025 en Año Fiscal, corresponde al mes de Octubre del año 2024 en calendario gregoriano.

In [18]:
drug_seizure_DF['Component'].unique()

array(['Air and Marine Operations'], dtype=object)

La columna 'Component' solo tiene 'Air and Marine Operations'.

In [16]:
drug_seizure_DF['Region'].unique()

array(['Coastal/Interior', 'Northern Border', 'Southwest Border'],
      dtype=object)

Para las distintas regiones, ver subsets de dataframes para cada una:

### Analisis Northern Border
Para Northern Border, qué tipos y cuántos de cada uno hay para las columnas 'Land Filter' y 'Branch'

In [34]:
drug_seizure_NorthernBorder = drug_seizure_DF[drug_seizure_DF['Region'].isin(['Northern Border'])]
drug_seizure_NorthernBorder

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
8,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Bellingham Air Branch,Cocaine,2,0.00
9,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Bellingham Air Branch,Fentanyl,1,0.73
10,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Bellingham Air Branch,Methamphetamine,1,0.07
11,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Cocaine,2,0.00
12,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Fentanyl,2,0.00
...,...,...,...,...,...,...,...,...,...
1286,2023,SEP,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Cocaine,1,9.70
1287,2023,SEP,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Fentanyl,2,0.55
1288,2023,SEP,Air and Marine Operations,Northern Border,Other,Great Lakes Air And Marine Branch,Cocaine,5,3.44
1289,2023,SEP,Air and Marine Operations,Northern Border,Other,Great Lakes Air And Marine Branch,Fentanyl,1,0.24
1290,2023,SEP,Air and Marine Operations,Northern Border,Other,Manassas Air Branch,Cocaine,3,0.29

In [31]:
drug_seizure_NorthernBorder.groupby('Land Filter').count()

,FY,Month (abbv),Component,Region,Branch,Drug Type,Count of Event,Sum Qty (lbs)
Land Filter,,,,,,,,
Land,274,274,274,274,274,274,274,274
Other,186,186,186,186,186,186,186,186

In [33]:
drug_seizure_NorthernBorder.groupby(['Branch','Land Filter']).count()

                                                FY  Month (abbv)  Component  \
Branch                            Land Filter
Bellingham Air Branch             Land         122           122        122
                                  Other          4             4          4
Great Lakes Air And Marine Branch Land          98            98         98
                                  Other         98            98         98
Manassas Air Branch               Land          21            21         21
                                  Other         83            83         83
NASOC - Grand Forks               Land          33            33         33
                                  Other          1             1          1

                                               Region  Drug Type  \
Branch                            Land Filter
Bellingham Air Branch             Land            122        122
                                  Other             4          4
Great Lakes Air And Marine Branch Land             98         98
                                  Other            98         98
Manassas Air Branch               Land             21         21
                                  Other            83         83
NASOC - Grand Forks               Land             33         33
                                  Other             1          1

                                               Count of Event  Sum Qty (lbs)
Branch                            Land Filter
Bellingham Air Branch             Land                    122            122
                                  Other                     4              4
Great Lakes Air And Marine Branch Land                     98             98
                                  Other                    98             98
Manassas Air Branch               Land                     21             21
                                  Other                    83             83
NASOC - Grand Forks               Land                     33             33
                                  Other                     1              1

Revisar geográficamente donde está cada rama. Centrarse en "Other", aunque, por ejemplo NASOC - Grand Forks puede ser importante.

### Analisis Southwest Border
Para Southwest Border, qué tipos y cuántos de cada uno hay para las columnas 'Land Filter' y 'Branch'

In [35]:
drug_seizure_SouthwestBorder = drug_seizure_DF[drug_seizure_DF['Region'].isin(['Southwest Border'])]
drug_seizure_SouthwestBorder

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
15,2025 (FYTD),NOV,Air and Marine Operations,Southwest Border,Land,Laredo Air Branch,Cocaine,2,4.60
16,2025 (FYTD),NOV,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Cocaine,3,5.60
17,2025 (FYTD),NOV,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Fentanyl,3,34.98
41,2025 (FYTD),OCT,Air and Marine Operations,Southwest Border,Land,El Paso Air Branch,Cocaine,1,17.64
42,2025 (FYTD),OCT,Air and Marine Operations,Southwest Border,Land,El Paso Air Branch,Fentanyl,1,30.87
...,...,...,...,...,...,...,...,...,...
1293,2023,SEP,Air and Marine Operations,Southwest Border,Land,NASOC - San Angelo,Cocaine,1,0.13
1294,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Cocaine,1,14.37
1295,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Fentanyl,1,2.45
1296,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Methamphetamine,1,5.73
1297,2023,SEP,Air and Marine Operations,Southwest Border,Other,San Diego Air And Marine Branch,Fentanyl,2,0.33

In [36]:
drug_seizure_SouthwestBorder.groupby(['Branch','Land Filter']).count()

                                             FY  Month (abbv)  Component  \
Branch                          Land Filter
El Paso Air Branch              Land          6             6          6
Ground Tactical Air Controller  Land         59            59         59
Laredo Air Branch               Land         39            39         39
                                Other         1             1          1
Mc Allen Air And Marine Branch  Land         48            48         48
NASOC - San Angelo              Land         42            42         42
                                Other        18            18         18
NASOC - Sierra Vista            Land         10            10         10
San Diego Air And Marine Branch Land          2             2          2
                                Other        52            52         52
Tucson Air Branch               Land         82            82         82
Yuma Air Branch                 Land         45            45         45

                                             Region  Drug Type  \
Branch                          Land Filter
El Paso Air Branch              Land              6          6
Ground Tactical Air Controller  Land             59         59
Laredo Air Branch               Land             39         39
                                Other             1          1
Mc Allen Air And Marine Branch  Land             48         48
NASOC - San Angelo              Land             42         42
                                Other            18         18
NASOC - Sierra Vista            Land             10         10
San Diego Air And Marine Branch Land              2          2
                                Other            52         52
Tucson Air Branch               Land             82         82
Yuma Air Branch                 Land             45         45

                                             Count of Event  Sum Qty (lbs)
Branch                          Land Filter
El Paso Air Branch              Land                      6              6
Ground Tactical Air Controller  Land                     59             59
Laredo Air Branch               Land                     39             39
                                Other                     1              1
Mc Allen Air And Marine Branch  Land                     48             48
NASOC - San Angelo              Land                     42             42
                                Other                    18             18
NASOC - Sierra Vista            Land                     10             10
San Diego Air And Marine Branch Land                      2              2
                                Other                    52             52
Tucson Air Branch               Land                     82             82
Yuma Air Branch                 Land                     45             45

Para 'southwest border' hay muchas localidades fronterizas de TX, AZ.
Quizá San Diego Air and Marine Branch pueda ser útil. Revisar NASOC.

### Análisis Coastal/Interior

In [37]:
drug_seizure_CoastalInterior = drug_seizure_DF[drug_seizure_DF['Region'].isin(['Coastal/Interior'])]
drug_seizure_CoastalInterior

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
0,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,AMOC Air And Marine Operations Center,Cocaine,1,1539.69
1,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,Ground Tactical Air Controller,Fentanyl,2,60.63
2,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Cocaine,1,5805.77
3,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Houston,Marijuana,1,9415.35
4,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Jacksonville,Cocaine,1,2657.03
...,...,...,...,...,...,...,...,...,...
1279,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,Jacksonville Air And Marine Branch,Fentanyl,2,0.27
1280,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,Jacksonville Air And Marine Branch,Methamphetamine,3,0.75
1281,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Cocaine,2,5249.16
1282,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Marijuana,1,1399.92
1283,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,NASOC - Jacksonville,Cocaine,2,4007.96

In [38]:
drug_seizure_CoastalInterior.groupby(['Branch','Land Filter']).count()

,,FY,Month (abbv),Component,Region,Drug Type,Count of Event,Sum Qty (lbs)
Branch,Land Filter,,,,,,,
AMOC Air And Marine Operations Center,Other,42,42,42,42,42,42,42
Caribbean Air And Marine Branch,Other,35,35,35,35,35,35,35
Ground Tactical Air Controller,Other,4,4,4,4,4,4,4
Houston Air And Marine Branch,Other,30,30,30,30,30,30,30
Jacksonville Air And Marine Branch,Other,103,103,103,103,103,103,103
Mexico City IAC,Other,10,10,10,10,10,10,10
Miami Air And Marine Branch,Other,28,28,28,28,28,28,28
NASOC - Albuquerque,Other,4,4,4,4,4,4,4
NASOC - Corpus Christi,Other,39,39,39,39,39,39,39
NASOC - Houston,Other,4,4,4,4,4,4,4
NASOC - Jacksonville,Other,53,53,53,53,53,53,53
National Air Training Center Oklahoma City,Other,4,4,4,4,4,4,4
New Orleans Air And Marine Branch,Other,78,78,78,78,78,78,78

En Resumen: de todas las observaciones, tienen preferencia aquellas con "Land Filter = 'Other'". Revisar las ciudades con respecto a su situación geográfica.

## 2. Exploracion de datos
Con yprofiling

In [ ]:
# 2. Exploracion de los datos

Extensión de la tabla a los años anteriores.
- Normalizar columna FY-Month: (%yyyy-MM)
- Union entre las tablas con misma estructura

In [ ]:
# 3. Visualizacion
# 4. Visualizacion en mapa

# Drug Seizure in the UK
To mars 2022

In [42]:
import xlrd

In [43]:
xlrd.__version__

'2.0.1'

In [44]:
# Extraer datos de las tablas: Area_Table_1 - Area_Table_6
ficheros_uk = '../home_uk/seizures-drugs-mar2022-tables-310322.xls'
uk_drug_seizure_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_1', # Lista con Area_Table_i donde i=1:6
                                   header=2,
                                   usecols="A:Q",
                                   skiprows=[6,12,17,23,28,35,38,44,50,51,56,57],
                                   engine='xlrd'
                                   )

In [45]:
uk_drug_seizure_df

,Police force region or authority,2006/07,2007/08,2008/09,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,2020/21,2021/22
0,Cleveland [note 16],3147,2496,2382,2462,1532,2140,1866,2017,2357,1935,1853,1900,1812,2432,2962,3135
1,Durham,2036,2060,1524,1497,1716,1590,1433,1756,1833,1569,1436,1620,1660,1704,1965,2043
2,Northumbria,4064,3648,5384,5011,5328,5584,5030,4797,4061,4044,3802,4121,4699,5069,5274,4400
3,Cheshire,736,1258,2024,2085,2223,1635,916,685,831,653,1064,2070,3138,1912,2085,1457
4,Cumbria,1416,1301,1201,1489,1536,1657,1408,1394,1244,942,870,834,968,896,1119,970
5,Greater Manchester,10137,12581,11952,10801,11740,11024,9214,7895,6249,4693,3948,4631,5351,7651,9509,7829
6,Lancashire,2866,3505,3816,4176,3812,3885,3311,2851,2326,1877,1167,1169,945,2303,2740,2401
7,Merseyside [note 14],1408,1745,13784,12946,1797,1948,1639,2452,2097,1629,550,582,655,1032,906,674
8,Humberside,2667,2458,2887,2817,2993,3196,2533,2316,1804,1390,1187,898,1023,1077,1733,1725
9,North Yorkshire,1397,1618,1602,1566,1731,1926,1511,1939,2204,1789,1990,1830,2145,2152,2233,2124
10,South Yorkshire,4225,4843,5514,6555,6020,6039,5826,5489,5243,4175,3797,3368,4248,4519,3766,3774
11,West Yorkshire,4600,2754,3410,3666,4555,5373,5808,5599,5008,4604,4924,5284,6046,7093,8342,8451
12,Derbyshire,3155,2134,2417,2722,3052,3287,3149,3292,3210,2858,2607,2720,2838,3393,2765,2328
13,Leicestershire,1831,2342,2655,2821,2899,2368,2267,2467,1559,1363,1830,2180,2749,2166,2652,3722
14,Lincolnshire,646,913,745,507,323,329,276,313,229,271,254,308,333,395,1239,1043
15,Northamptonshire,1893,1267,1354,1501,2147,1882,2170,2631,2542,2091,1536,1563,2055,2041,2154,2506
16,Nottinghamshire,3946,4869,4116,2273,2528,4657,4924,5009,4303,4006,3596,3224,3403,4097,4459,4163
17,Staffordshire,2667,3956,3325,3297,3224,3990,3789,3633,3312,2631,2527,2713,2557,2596,1064,2420
18,Warwickshire,1360,1293,1289,1551,1273,1009,1236,920,1158,1234,1267,1266,1446,1116,1262,873
19,West Mercia,3333,3303,3007,3113,3145,3369,3391,2617,3419,3447,3195,2900,3292,3492,4148,2948
20,West Midlands,10732,10389,10608,9596,9143,9701,8632,7546,6036,5997,5163,4722,5573,6727,7086,4735
21,Bedfordshire,802,960,1348,1101,1837,1994,1699,1592,1330,1163,1245,1209,1220,1398,1777,1494
22,Cambridgeshire,2263,2843,2628,2270,2019,2467,2471,2619,2563,1985,2001,1862,2332,2430,2810,2405
23,Essex,1949,2748,3988,3321,4281,3655,3224,3336,3478,3042,3127,3098,3620,5217,7250,5567
24,Hertfordshire,2808,2954,3640,4933,4660,4974,4250,4655,3640,3276,3059,3144,3399,4031,4614,3886
25,Norfolk [note 16],1093,1088,569,598,870,2100,2735,3284,2931,1767,1526,1936,2607,3501,5090,5428
26,Suffolk,1372,1249,1170,1014,962,1307,1482,1237,1172,1343,2272,3045,2770,3626,3390,3794
27,"London, City of",900,883,690,771,658,631,497,371,416,328,317,322,321,491,478,590
28,Metropolitan Police,54458,71404,76390,66511,62714,59847,49832,48772,41141,37625,33560,30716,31594,41469,50737,40693
29,Hampshire,1907,3786,4433,5258,5044,5465,4783,4494,3753,2965,3241,3378,3962,4909,6393,5770
30,Kent [note 15],2363,2529,2404,2767,4934,4979,5316,5295,4233,3841,3635,3569,3858,4576,5238,4411
31,Surrey,1499,1817,1836,1693,2040,2091,1830,1744,1584,1144,1004,1462,1694,1629,1181,960
32,Sussex,6087,7529,6141,6373,6364,6738,6415,6149,6021,5352,5555,5497,5954,6216,5534,5096
33,Thames Valley,7551,8167,8425,7666,7160,7269,6794,6543,3489,4405,917,659,736,1039,1608,679
34,Avon & Somerset,5241,5907,6437,6383,6882,7675,7175,6076,4136,4120,3783,3109,4324,4882,4075,2916
35,Devon & Cornwall [note 16],4874,4640,4057,2823,2884,4488,4523,3901,3232,2582,4360,4078,4521,4960,5658,4848
36,Dorset,1541,1721,1873,1903,1952,2103,2066,1887,1885,1649,1768,1989,2097,1896,2051,1799
37,Gloucestershire,1343,1811,2308,2322,1976,2096,2158,1705,1431,1392,1381,1391,1177,1480,2098,1658
38,Wiltshire,707,569,972,1138,1354,1698,1688,1733,1092,1530,2306,948,1514,1624,1849,1453
39,Dyfed-Powys,2359,2181,2237,2630,2876,3354,3358,3192,2749,2416,1969,1798,2032,2110,2219,1619
40,Gwent,1815,2020,2302,2107,2268,2489,2301,2279,1285,1281,1079,997,1015,983,1223,846
41,North Wales,1920,2374,2531,2441,2181,1744,1571,1743,1676,1389,1083,1189,2034,2175,2210,1849
42,South Wales,4607,6554,6720,6245,6029,5801,5109,4642,4365,4144,3628,3509,4223,4411,5056,3696
43,Police Total,180409,210272,233793,220453,208832,215117,194901,188732,160805,143405,132515,130107,144378,171252,195566,168050
44,Border Force,6516,6588,7680,3948,3954,3588,5695,5847,6199,5366,6736,6499,8937,13844,24012,20877
45,TOTAL ENGLAND AND WALES,186925,216860,241473,224401,212786,218705,200596,194579,167004,148771,139251,136606,153315,185096,219578,188927

 - Extender datos para Area_Table 2:6
 - Normalizar entrada de Hojas de excel.
 - ¿Se podrá hacer la extensión en columnas por cada nueva hoja excel que se añada?
 - Añadir nueva columna con la region asociada