In [1]:
import pandas as pd

## Drug Seizure in USA
Y primera inspección de los mismos

In [2]:
# 1. Cargar ficheros de CBP_drug_seizures
files = '../CBP_drug_seizures/amo-drug-seizures-fy22-fy25-nov.csv' # Generar mascara para obtener todos los csv de la carpeta
drug_seizure_DF = pd.read_csv(files,sep=',') # header = infer

In [3]:
drug_seizure_DF

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
0,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,AMOC Air And Marine Operations Center,Cocaine,1,1539.69
1,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,Ground Tactical Air Controller,Fentanyl,2,60.63
2,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Cocaine,1,5805.77
3,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Houston,Marijuana,1,9415.35
4,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Jacksonville,Cocaine,1,2657.03
...,...,...,...,...,...,...,...,...,...
1293,2023,SEP,Air and Marine Operations,Southwest Border,Land,NASOC - San Angelo,Cocaine,1,0.13
1294,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Cocaine,1,14.37
1295,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Fentanyl,1,2.45
1296,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Methamphetamine,1,5.73
1297,2023,SEP,Air and Marine Operations,Southwest Border,Other,San Diego Air And Marine Branch,Fentanyl,2,0.33

FY: hace referencia a 'Fiscal Year' que en USA empiza a contar el 1 de octubre del año "anterior". Es decir, October 2025 en Año Fiscal, corresponde al mes de Octubre del año 2024 en calendario gregoriano.

In [4]:
drug_seizure_DF['Component'].unique()

array(['Air and Marine Operations'], dtype=object)

La columna 'Component' solo tiene 'Air and Marine Operations'.

In [5]:
drug_seizure_DF['Region'].unique()

array(['Coastal/Interior', 'Northern Border', 'Southwest Border'],
      dtype=object)

Para las distintas regiones, ver subsets de dataframes para cada una:

### Analisis Northern Border
Para Northern Border, qué tipos y cuántos de cada uno hay para las columnas 'Land Filter' y 'Branch'

In [6]:
drug_seizure_NorthernBorder = drug_seizure_DF[drug_seizure_DF['Region'].isin(['Northern Border'])]
drug_seizure_NorthernBorder

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
8,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Bellingham Air Branch,Cocaine,2,0.00
9,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Bellingham Air Branch,Fentanyl,1,0.73
10,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Bellingham Air Branch,Methamphetamine,1,0.07
11,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Cocaine,2,0.00
12,2025 (FYTD),NOV,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Fentanyl,2,0.00
...,...,...,...,...,...,...,...,...,...
1286,2023,SEP,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Cocaine,1,9.70
1287,2023,SEP,Air and Marine Operations,Northern Border,Land,Great Lakes Air And Marine Branch,Fentanyl,2,0.55
1288,2023,SEP,Air and Marine Operations,Northern Border,Other,Great Lakes Air And Marine Branch,Cocaine,5,3.44
1289,2023,SEP,Air and Marine Operations,Northern Border,Other,Great Lakes Air And Marine Branch,Fentanyl,1,0.24
1290,2023,SEP,Air and Marine Operations,Northern Border,Other,Manassas Air Branch,Cocaine,3,0.29

In [7]:
drug_seizure_NorthernBorder.groupby('Land Filter').count()

,FY,Month (abbv),Component,Region,Branch,Drug Type,Count of Event,Sum Qty (lbs)
Land Filter,,,,,,,,
Land,274,274,274,274,274,274,274,274
Other,186,186,186,186,186,186,186,186

In [8]:
drug_seizure_NorthernBorder.groupby(['Branch','Land Filter']).count()

                                                FY  Month (abbv)  Component  \
Branch                            Land Filter
Bellingham Air Branch             Land         122           122        122
                                  Other          4             4          4
Great Lakes Air And Marine Branch Land          98            98         98
                                  Other         98            98         98
Manassas Air Branch               Land          21            21         21
                                  Other         83            83         83
NASOC - Grand Forks               Land          33            33         33
                                  Other          1             1          1

                                               Region  Drug Type  \
Branch                            Land Filter
Bellingham Air Branch             Land            122        122
                                  Other             4          4
Great Lakes Air And Marine Branch Land             98         98
                                  Other            98         98
Manassas Air Branch               Land             21         21
                                  Other            83         83
NASOC - Grand Forks               Land             33         33
                                  Other             1          1

                                               Count of Event  Sum Qty (lbs)
Branch                            Land Filter
Bellingham Air Branch             Land                    122            122
                                  Other                     4              4
Great Lakes Air And Marine Branch Land                     98             98
                                  Other                    98             98
Manassas Air Branch               Land                     21             21
                                  Other                    83             83
NASOC - Grand Forks               Land                     33             33
                                  Other                     1              1

Revisar geográficamente donde está cada rama. Centrarse en "Other", aunque, por ejemplo NASOC - Grand Forks puede ser importante.

### Analisis Southwest Border
Para Southwest Border, qué tipos y cuántos de cada uno hay para las columnas 'Land Filter' y 'Branch'

In [9]:
drug_seizure_SouthwestBorder = drug_seizure_DF[drug_seizure_DF['Region'].isin(['Southwest Border'])]
drug_seizure_SouthwestBorder

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
15,2025 (FYTD),NOV,Air and Marine Operations,Southwest Border,Land,Laredo Air Branch,Cocaine,2,4.60
16,2025 (FYTD),NOV,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Cocaine,3,5.60
17,2025 (FYTD),NOV,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Fentanyl,3,34.98
41,2025 (FYTD),OCT,Air and Marine Operations,Southwest Border,Land,El Paso Air Branch,Cocaine,1,17.64
42,2025 (FYTD),OCT,Air and Marine Operations,Southwest Border,Land,El Paso Air Branch,Fentanyl,1,30.87
...,...,...,...,...,...,...,...,...,...
1293,2023,SEP,Air and Marine Operations,Southwest Border,Land,NASOC - San Angelo,Cocaine,1,0.13
1294,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Cocaine,1,14.37
1295,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Fentanyl,1,2.45
1296,2023,SEP,Air and Marine Operations,Southwest Border,Land,Tucson Air Branch,Methamphetamine,1,5.73
1297,2023,SEP,Air and Marine Operations,Southwest Border,Other,San Diego Air And Marine Branch,Fentanyl,2,0.33

In [10]:
drug_seizure_SouthwestBorder.groupby(['Branch','Land Filter']).count()

                                             FY  Month (abbv)  Component  \
Branch                          Land Filter
El Paso Air Branch              Land          6             6          6
Ground Tactical Air Controller  Land         59            59         59
Laredo Air Branch               Land         39            39         39
                                Other         1             1          1
Mc Allen Air And Marine Branch  Land         48            48         48
NASOC - San Angelo              Land         42            42         42
                                Other        18            18         18
NASOC - Sierra Vista            Land         10            10         10
San Diego Air And Marine Branch Land          2             2          2
                                Other        52            52         52
Tucson Air Branch               Land         82            82         82
Yuma Air Branch                 Land         45            45         45

                                             Region  Drug Type  \
Branch                          Land Filter
El Paso Air Branch              Land              6          6
Ground Tactical Air Controller  Land             59         59
Laredo Air Branch               Land             39         39
                                Other             1          1
Mc Allen Air And Marine Branch  Land             48         48
NASOC - San Angelo              Land             42         42
                                Other            18         18
NASOC - Sierra Vista            Land             10         10
San Diego Air And Marine Branch Land              2          2
                                Other            52         52
Tucson Air Branch               Land             82         82
Yuma Air Branch                 Land             45         45

                                             Count of Event  Sum Qty (lbs)
Branch                          Land Filter
El Paso Air Branch              Land                      6              6
Ground Tactical Air Controller  Land                     59             59
Laredo Air Branch               Land                     39             39
                                Other                     1              1
Mc Allen Air And Marine Branch  Land                     48             48
NASOC - San Angelo              Land                     42             42
                                Other                    18             18
NASOC - Sierra Vista            Land                     10             10
San Diego Air And Marine Branch Land                      2              2
                                Other                    52             52
Tucson Air Branch               Land                     82             82
Yuma Air Branch                 Land                     45             45

Para 'southwest border' hay muchas localidades fronterizas de TX, AZ.
Quizá San Diego Air and Marine Branch pueda ser útil. Revisar NASOC.

### Análisis Coastal/Interior

In [11]:
drug_seizure_CoastalInterior = drug_seizure_DF[drug_seizure_DF['Region'].isin(['Coastal/Interior'])]
drug_seizure_CoastalInterior

,FY,Month (abbv),Component,Region,Land Filter,Branch,Drug Type,Count of Event,Sum Qty (lbs)
0,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,AMOC Air And Marine Operations Center,Cocaine,1,1539.69
1,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,Ground Tactical Air Controller,Fentanyl,2,60.63
2,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Cocaine,1,5805.77
3,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Houston,Marijuana,1,9415.35
4,2025 (FYTD),NOV,Air and Marine Operations,Coastal/Interior,Other,NASOC - Jacksonville,Cocaine,1,2657.03
...,...,...,...,...,...,...,...,...,...
1279,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,Jacksonville Air And Marine Branch,Fentanyl,2,0.27
1280,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,Jacksonville Air And Marine Branch,Methamphetamine,3,0.75
1281,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Cocaine,2,5249.16
1282,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,NASOC - Corpus Christi,Marijuana,1,1399.92
1283,2023,SEP,Air and Marine Operations,Coastal/Interior,Other,NASOC - Jacksonville,Cocaine,2,4007.96

In [12]:
drug_seizure_CoastalInterior.groupby(['Branch','Land Filter']).count()

,,FY,Month (abbv),Component,Region,Drug Type,Count of Event,Sum Qty (lbs)
Branch,Land Filter,,,,,,,
AMOC Air And Marine Operations Center,Other,42,42,42,42,42,42,42
Caribbean Air And Marine Branch,Other,35,35,35,35,35,35,35
Ground Tactical Air Controller,Other,4,4,4,4,4,4,4
Houston Air And Marine Branch,Other,30,30,30,30,30,30,30
Jacksonville Air And Marine Branch,Other,103,103,103,103,103,103,103
Mexico City IAC,Other,10,10,10,10,10,10,10
Miami Air And Marine Branch,Other,28,28,28,28,28,28,28
NASOC - Albuquerque,Other,4,4,4,4,4,4,4
NASOC - Corpus Christi,Other,39,39,39,39,39,39,39
NASOC - Houston,Other,4,4,4,4,4,4,4
NASOC - Jacksonville,Other,53,53,53,53,53,53,53
National Air Training Center Oklahoma City,Other,4,4,4,4,4,4,4
New Orleans Air And Marine Branch,Other,78,78,78,78,78,78,78

En Resumen: de todas las observaciones, tienen preferencia aquellas con "Land Filter = 'Other'". Revisar las ciudades con respecto a su situación geográfica.

Reuniendo todas las regiones, la agrupación por 'Branch' y 'Land Filter' queda de la siguiente manera:

In [16]:
drug_seizure_DF.groupby(['Branch','Land Filter'])[['Count of Event','Sum Qty (lbs)']].sum().sort_values(by='Count of Event', ascending = False)

                                                        Count of Event  \
Branch                                     Land Filter
Bellingham Air Branch                      Land                    540
Jacksonville Air And Marine Branch         Other                   364
Great Lakes Air And Marine Branch          Other                   294
                                           Land                    258
Manassas Air Branch                        Other                   220
Tucson Air Branch                          Land                    202
NASOC - Jacksonville                       Other                   156
Ground Tactical Air Controller             Land                    145
New Orleans Air And Marine Branch          Other                   124
San Diego Air And Marine Branch            Other                   105
Mc Allen Air And Marine Branch             Land                     92
Houston Air And Marine Branch              Other                    90
AMOC Air And Marine Operations Center      Other                    78
Yuma Air Branch                            Land                     78
NASOC - Corpus Christi                     Other                    76
NASOC - Grand Forks                        Land                     71
Caribbean Air And Marine Branch            Other                    64
Laredo Air Branch                          Land                     63
NASOC - San Angelo                         Land                     62
Miami Air And Marine Branch                Other                    50
NASOC - San Angelo                         Other                    43
Manassas Air Branch                        Land                     34
Ground Tactical Air Controller             Other                    13
NASOC - Sierra Vista                       Land                     12
Mexico City IAC                            Other                    10
NASOC - Houston                            Other                     7
National Air Training Center Oklahoma City Other                     7
El Paso Air Branch                         Land                      6
NASOC - Albuquerque                        Other                     5
Bellingham Air Branch                      Other                     5
San Diego Air And Marine Branch            Land                      2
Laredo Air Branch                          Other                     1
NASOC - Grand Forks                        Other                     1

                                                        Sum Qty (lbs)
Branch                                     Land Filter
Bellingham Air Branch                      Land              17551.84
Jacksonville Air And Marine Branch         Other             60531.62
Great Lakes Air And Marine Branch          Other              4240.63
                                           Land               5686.32
Manassas Air Branch                        Other              3395.11
Tucson Air Branch                          Land               1927.48
NASOC - Jacksonville                       Other            302040.86
Ground Tactical Air Controller             Land                923.09
New Orleans Air And Marine Branch          Other             12594.45
San Diego Air And Marine Branch            Other              3557.37
Mc Allen Air And Marine Branch             Land               2781.13
Houston Air And Marine Branch              Other              3837.30
AMOC Air And Marine Operations Center      Other             65868.36
Yuma Air Branch                            Land               1207.59
NASOC - Corpus Christi                     Other            173614.55
NASOC - Grand Forks                        Land                 82.08
Caribbean Air And Marine Branch            Other             27095.42
Laredo Air Branch                          Land               4655.90
NASOC - San Angelo                         Land               6311.52
Miami Air And Marine Branch                Other              7763.49
NASOC - San Angelo                         Other             80901.92
Manassas Air Branch                        Land                228.44
Ground Tactical Air Controller             Other               107.59
NASOC - Sierra Vista                       Land              11296.87
Mexico City IAC                            Other              4317.68
NASOC - Houston                            Other             31375.16
National Air Training Center Oklahoma City Other                 2.29
El Paso Air Branch                         Land                 99.41
NASOC - Albuquerque                        Other                 3.43
Bellingham Air Branch                      Other              7381.00
San Diego Air And Marine Branch            Land                  2.29
Laredo Air Branch                          Other                 0.01
NASOC - Grand Forks                        Other              1708.98

Donde están situadas geográficamente las ramas del CBP:
- Bellingham Air Branch: Seattle, frontera con Canada
- Jacksonville Air And Marine Branch + NASOC - Jacksonville: Jacksonville (FL)
- Great Lakes Air And Marine Branch: Chicago (IL), Kenosha (WI)
- Manassas Air Branch: Washington DC, Norfolk (VI)
- New Orleans Air And Marine Branch: Nueva Orleans (LO)
- San Diego Air And Marine Branch: San Diego (CA)
- Houston Air And Marine Branch: Houston (TX)
- AMOC Air And Marine Operations Center: Los Angeles (CA)
- NASOC - Corpus Christi: Corpus Christi (TX)
- Caribbean Air And Marine Branch: Puerto Rico
- Miami Air And Marine Branch: Miami & Fort Lauderdale (FL)

## Drug Seizure USA (2019)

Ahora vamos a cargar los datos para los años fiscales 2019 (Octubre 2018) a 2022

In [2]:
files = '../CBP_drug_seizures/nationwide-drugs-fy19-fy22.csv' # Generar mascara para obtener todos los csv de la carpeta
drug_seizure_2019_DF = pd.read_csv(files,sep=',') # header = infer

Extraemos año 2019:

In [7]:
drug_seizure_2019_DF = drug_seizure_2019_DF.loc[drug_seizure_2019_DF["FY"] == 2019]

Año 2020, 21:

In [8]:
files = '../CBP_drug_seizures/nationwide-drugs-fy20-fy23.csv' # Generar mascara para obtener todos los csv de la carpeta
drug_seizure_2020_DF = pd.read_csv(files,sep=',') # header = infer
drug_seizure_2020_DF = drug_seizure_2020_DF.loc[drug_seizure_2020_DF["FY"] == 2020]

In [10]:
files = '../CBP_drug_seizures/nationwide-drugs-fy21-fy24.csv' # Generar mascara para obtener todos los csv de la carpeta
drug_seizure_2021_DF = pd.read_csv(files,sep=',') # header = infer
drug_seizure_2021_DF = drug_seizure_2021_DF.loc[drug_seizure_2021_DF["FY"] == 2021]

In [13]:
files = '../CBP_drug_seizures/nationwide-drugs-fy22-fy25-dec.csv' # Generar mascara para obtener todos los csv de la carpeta
drug_seizure_2022_25_DF = pd.read_csv(files,sep=',') # header = infer

In [14]:
drug_seizure_2022_25_DF

,FY,Month (abbv),Component,Region,Land Filter,Area of Responsibility,Drug Type,Count of Event,Sum Qty (lbs)
0,2025 (FYTD),DEC,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Ecstasy,1,0.825190
1,2025 (FYTD),DEC,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Marijuana,3,3.435243
2,2025 (FYTD),DEC,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Other Drugs**,6,21.752350
3,2025 (FYTD),DEC,Office of Field Operations,Coastal/Interior,Other,BALTIMORE FIELD OFFICE,Cocaine,3,0.776600
4,2025 (FYTD),DEC,Office of Field Operations,Coastal/Interior,Other,BALTIMORE FIELD OFFICE,Fentanyl,3,0.862757
...,...,...,...,...,...,...,...,...,...
7947,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,TUCSON SECTOR,Other Drugs**,4,0.222700
7948,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Fentanyl,2,4.952400
7949,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Marijuana,11,0.412100
7950,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Methamphetamine,2,84.452600
7951,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Other Drugs**,2,1.748300

Concatenar dataframes de 2019 a 2025:

In [82]:
cbp_seizure_dataframe = pd.concat([drug_seizure_2019_DF, drug_seizure_2020_DF, drug_seizure_2021_DF, drug_seizure_2022_25_DF], axis = 0, ignore_index=True, join='outer')

In [83]:
month_map = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

# Convertir 'Month' a número
cbp_seizure_dataframe['Month_Num'] = cbp_seizure_dataframe['Month (abbv)'].map(month_map)

cbp_seizure_dataframe['FY'] = cbp_seizure_dataframe['FY'].replace({'2025 (FYTD)': '2025'})
cbp_seizure_dataframe['FY'] = pd.to_numeric(cbp_seizure_dataframe['FY'], downcast='integer', errors='coerce')

In [84]:
# Ajustar el año fiscal (suponiendo que el FY comienza en OCT)
cbp_seizure_dataframe['Year'] = cbp_seizure_dataframe['FY']
cbp_seizure_dataframe.loc[cbp_seizure_dataframe['Month_Num'] >= 10, 'Year'] = cbp_seizure_dataframe['FY'] - 1

cbp_seizure_dataframe.rename(columns={'Month_Num':'Month'}, inplace=True)

In [89]:
cbp_seizure_dataframe['Year'].unique()

array([2019, 2018, 2020, 2021, 2024, 2023, 2022], dtype=int16)

In [86]:
# Crear la nueva columna con formato YYYY-MM
cbp_seizure_dataframe['Date'] = pd.to_datetime(cbp_seizure_dataframe[['Year', 'Month']].assign(day=1)).dt.strftime('%Y-%m')

Añadir el identificador de cluster del hub portuario, segun diccionario para luego agregarlo en los datos de tratamiento

In [92]:
cbp_seizure_dataframe['Sum Qty (kg)'] = cbp_seizure_dataframe['Sum Qty (lbs)']/2.20462

In [108]:
cbp_seizure_dataframe

,FY,Month (abbv),Component,Region,Land Filter,Area of Responsibility,Drug Type,Count of Event,Sum Qty (lbs),Month,Year,Date,Sum Qty (kg)
0,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Ecstasy,3,8.379947,4,2019,2019-04,3.801085
1,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Khat (Catha Edulis),4,1394.423807,4,2019,2019-04,632.500752
2,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Marijuana,5,0.089397,4,2019,2019-04,0.040550
3,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Other Drugs**,8,42.663196,4,2019,2019-04,19.351723
4,2019,APR,Office of Field Operations,Coastal/Interior,Other,BALTIMORE FIELD OFFICE,Cocaine,3,8.542913,4,2019,2019-04,3.875005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15560,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,TUCSON SECTOR,Other Drugs**,4,0.222700,9,2023,2023-09,0.101015
15561,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Fentanyl,2,4.952400,9,2023,2023-09,2.246374
15562,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Marijuana,11,0.412100,9,2023,2023-09,0.186926
15563,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Methamphetamine,2,84.452600,9,2023,2023-09,38.307101
15564,2023,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Other Drugs**,2,1.748300,9,2023,2023-09,0.793016

In [90]:
cbp_seizure_dataframe['Area of Responsibility'].unique()

array(['ATLANTA FIELD OFFICE', 'BALTIMORE FIELD OFFICE',
       'CHICAGO FIELD OFFICE', 'HOUSTON FIELD OFFICE',
       'LOS ANGELES FIELD OFFICE', 'MIAMI FIELD OFFICE',
       'NEW ORLEANS FIELD OFFICE', 'NEW YORK FIELD OFFICE',
       'PRECLEARANCE FIELD OFFICE', 'SAN FRANCISCO FIELD OFFICE',
       'SAN JUAN FIELD OFFICE', 'TAMPA FIELD OFFICE',
       'BOSTON FIELD OFFICE', 'BUFFALO FIELD OFFICE',
       'DETROIT FIELD OFFICE', 'SEATTLE FIELD OFFICE',
       'PORTLAND FIELD OFFICE', 'EL PASO FIELD OFFICE',
       'LAREDO FIELD OFFICE', 'SAN DIEGO FIELD OFFICE',
       'TUCSON FIELD OFFICE', 'MIAMI SECTOR', 'BLAINE SECTOR',
       'BUFFALO SECTOR', 'DETROIT SECTOR', 'HAVRE SECTOR',
       'HOULTON SECTOR', 'SPOKANE SECTOR', 'SWANTON SECTOR',
       'BIG BEND SECTOR', 'DEL RIO SECTOR', 'EL CENTRO SECTOR',
       'EL PASO SECTOR', 'LAREDO SECTOR', 'RIO GRANDE VALLEY SECTOR',
       'SAN DIEGO SECTOR', 'TUCSON SECTOR', 'YUMA SECTOR',
       'NEW ORLEANS SECTOR', 'RAMEY SECTOR', 'GRAND FORKS SECTOR'],
      dtype=object)

In [98]:
# Info 'drug_seizure_uk'
uk_seizure_df = pd.read_csv('../home_uk/uk_drug_seizure_df.csv', sep=',')
uk_seizure_df = uk_seizure_df.loc[:,['Police force region or authority','2018/19','2019/20','2020/21','2021/22']]

In [109]:
# Melt the DataFrame
uk_seizure_df_long = uk_seizure_df.melt(id_vars='Police force region or authority', 
                 var_name='Year', 
                 value_name='Count of Event')

In [111]:
uk_seizure_df_long['Year'] = uk_seizure_df_long['Year'].str.split('/').str[0]
uk_seizure_df_long['Date'] = pd.to_datetime(uk_seizure_df_long['Year'] + '-04-01').dt.strftime('%Y-%m')

In [119]:
uk_seizure_df_long.columns

Index(['Police force region or authority', 'Year', 'Count of Event', 'Date'], dtype='object')

In [114]:
uk_drug_seizure_df_wide = pd.read_csv('../home_uk/uk_drug_seizure_kg_df.csv',sep=',')
uk_drug_seizure_df_wide

,Police force region or authority,Cocaine,Crack,Ecstasy (MDMA),Heroin,LSD,Methadone,Morphine,Cannabis (Herbal),Cannabis (Resin),Cannabis Plants,Amphetamines,Barbiturates,Ketamine,Anabolic Steroids,Benzodiazepines,GHB,Temazepam
0,Cleveland,5.93,0.81,0.46,1.54,0.01,4.47,3.42,66.17,0.42,6817.00,9.90,0.00,0.00,0.72,16.52,0.00,9.87
1,Durham,1.41,0.08,0.18,1.17,0.00,0.20,0.42,8.75,1.09,15009.00,0.95,0.00,0.00,0.36,3.13,0.00,0.30
2,Northumbria,62.23,0.62,10.05,10.39,0.14,2.23,0.94,214.76,13.07,29493.00,3.59,0.00,2.20,4.39,31.10,0.00,0.87
3,Cheshire,2.27,0.40,0.13,0.40,0.01,0.01,0.11,8.59,0.34,1443.00,1.71,0.00,0.05,0.00,0.38,0.00,0.00
4,Cumbria,10.90,1.06,8.39,4.82,0.01,0.20,0.00,84.73,0.49,6448.00,8.23,0.00,0.64,0.00,10.44,0.00,0.01
5,Greater Manchester,1.66,0.43,0.31,0.51,0.03,0.15,0.00,69.10,6.62,14783.00,0.20,0.00,0.06,0.23,3.86,0.00,0.00
6,Lancashire,6.30,1.37,0.39,16.70,0.04,0.94,0.00,109.94,4.26,44401.00,6.90,0.00,0.60,1.40,13.43,0.00,0.03
7,Merseyside,29.83,2.25,0.00,35.31,0.00,0.36,0.00,3.71,5.63,44226.00,31.13,0.00,16.69,0.73,3.45,0.00,0.00
8,Humberside,2.94,3.44,0.01,1.79,0.00,1.17,0.00,57.88,0.00,5527.00,2.80,0.00,0.07,0.09,0.14,0.00,0.00
9,North Yorkshire,1.36,0.04,2.55,0.16,0.01,0.00,0.01,19.14,0.07,1198.00,0.04,0.00,0.05,0.01,0.21,0.00,0.00
10,South Yorkshire,2.05,0.14,0.27,0.22,0.00,1.18,0.03,101.89,3.48,230069.00,0.11,0.00,0.34,8.95,2.34,0.00,0.00
11,West Yorkshire,1.44,0.22,0.15,0.18,0.02,0.07,0.12,50.31,5.98,19947.00,0.18,0.00,0.02,0.24,1.36,0.00,0.00
12,Derbyshire,3.28,1.35,0.62,1.91,0.37,1.81,0.10,124.81,0.16,6940.20,2.25,0.00,0.24,0.39,1.06,0.04,0.03
13,Leicestershire,4.68,0.97,38.87,4.14,0.03,56.42,1.00,611.52,1.13,41576.00,0.98,0.00,0.10,2.82,2.14,0.02,0.00
14,Lincolnshire,0.05,0.00,0.01,0.14,0.00,1.56,0.27,12.27,0.16,13102.98,0.03,0.00,0.03,0.00,0.05,0.00,0.01
15,Northamptonshire,0.58,0.28,0.58,0.15,0.01,0.06,0.21,28.52,1.35,15853.00,0.06,0.00,0.04,0.00,0.14,0.00,0.00
16,Nottinghamshire,6.75,7.80,6.12,0.13,0.01,0.00,0.00,104.04,1.78,15615.00,0.69,0.00,0.06,0.00,0.03,0.00,0.00
17,Staffordshire,31.92,0.80,0.31,4.55,0.10,0.77,0.15,129.03,1.19,24578.00,0.99,0.01,9.91,0.26,1.46,0.00,0.00
18,Warwickshire,0.65,0.17,0.12,0.08,0.04,0.16,0.01,12.61,3.36,3270.00,0.03,0.00,0.00,0.00,0.17,0.00,0.02
19,West Mercia,1.50,0.42,0.45,0.39,0.25,1.54,0.13,31.45,2.55,6531.00,0.06,0.00,0.01,0.92,0.72,0.00,0.00
20,West Midlands,53.40,0.18,0.05,23.19,0.00,0.12,0.00,64.62,1.76,23261.00,0.31,0.00,0.00,0.00,0.07,0.00,0.00
21,Bedfordshire,6.98,0.45,1.22,15.54,0.09,0.20,0.11,30.91,1.07,6498.00,0.05,0.00,0.08,0.00,0.33,0.00,0.00
22,Cambridgeshire,34.76,0.60,2.35,11.29,0.28,0.09,0.15,219.04,0.69,13529.00,1.92,0.00,0.15,16.87,6.82,0.07,0.00
23,Essex,194.16,0.39,1.71,1.34,0.28,0.03,0.00,598.72,0.51,10027.00,9.02,0.00,0.11,16.00,0.27,0.00,0.02
24,Hertfordshire,6.84,0.02,0.22,10.38,0.00,0.01,0.00,140.45,0.02,17171.45,0.02,0.00,0.00,0.00,0.00,0.00,0.00
25,Norfolk,0.01,0.01,0.00,0.00,0.00,1.25,0.00,135.32,1.40,1271.00,0.00,0.00,0.00,0.00,0.14,0.00,0.03
26,Suffolk,1.09,0.15,0.00,0.04,0.00,1.15,0.00,40.67,1.35,3872.00,0.08,0.00,0.00,0.01,0.01,0.00,0.00
27,"London, City of",0.79,0.01,0.19,0.03,0.00,0.01,0.00,4.47,0.61,0.00,0.03,0.00,0.02,0.00,0.68,0.00,0.00
28,Metropolitan Police,1047.82,11.84,52.16,109.47,1.89,0.78,0.11,11263.42,58.57,40241.00,10.70,0.00,113.90,0.37,3.29,7.74,0.00
29,Hampshire,26.09,1.27,0.54,0.39,10.24,1.17,0.02,678.76,47.33,12509.00,1.39,0.00,0.08,0.69,1.50,0.02,0.00
30,Kent,14.89,0.19,1.58,0.39,0.13,0.02,0.01,112.44,0.91,8997.93,0.60,0.00,0.04,0.00,0.00,0.00,0.00
31,Surrey,18.26,0.62,6.96,1.16,3.51,0.59,0.21,286.58,3.55,3648.00,0.02,0.00,0.69,0.26,3.17,0.00,0.00
32,Sussex,6.76,0.43,5.61,0.50,0.03,0.32,0.63,73.06,2.63,4114.00,3.81,0.00,0.01,0.14,0.22,0.00,0.00
33,Thames Valley,0.18,0.07,0.11,0.08,0.03,0.00,0.00,2.62,0.43,1334.00,0.00,0.00,0.04,0.00,0.16,0.00,0.00
34,Avon & Somerset,16.75,0.98,1.82,10.17,0.12,0.85,0.05,75.81,1.83,12191.00,1.44,0.00,19.75,1.41,16.29,0.00,0.00
35,Devon & Cornwall,18.67,0.60,6.16,3.98,0.30,6.94,0.64,157.34,3.41,3928.00,18.71,0.00,1.76,1.45,25.26,0.00,7.50
36,Dorset,12.22,0.30,0.67,0.56,0.03,1.77,2.82,52.38,0.31,1811.00,0.20,0.00,0.33,0.96,1.38,0.01,0.14
37,Gloucestershire,1.43,0.65,0.32,1.27,0.03,0.06,0.41,31.50,0.62,36313.00,3.62,0.00,0.07,0.00,1.28,0.00,0.01
38,Wiltshire,4.23,0.19,0.34,4.89,0.00,0.61,0.10,45.02,0.30,1040.00,1.23,0.00,0.15,0.08,0.55,0.00,0.00
39,Dyfed-Powys,1.34,0.01,10.38,0.21,113.19,0.08,0.01,24.84,0.59,3013.00,0.60,0.00,0.03,0.05,8.89,0.00,0.02
40,Gwent,0.38,0.32,0.12,0.13,0.00,0.00,0.00,5.27,0.27,2461.00,0.51,0.00,0.01,0.00,0.39,0.00,0.00
41,North Wales,14.09,0.14,0.17,1.53,0.00,1.58,0.01,42.79,0.69,614.00,8.83,0.00,2.97,2.65,0.00,0.00,0.02
42,South Wales,20.45,1.17,1.43,13.81,0.26,13.02,0.02,156.62,2.02,30267.00,28.45,0.00,0.85,1.68,44.87,0.00,0.03
43,Police Total,1680.02,43.35,164.82,295.53,131.53,104.12,12.33,16138.42,188.26,785907.56,163.15,0.02,172.92,64.21,210.89,7.90,18.96
44,"Border Force [notes 7, 8]",17087.37,0.01,432.15,1116.51,30.41,0.53,0.42,19297.79,422.44,47.00,80.01,0.00,1663.60,2437.20,0.00,13.31,3.58
45,TOTAL ENGLAND AND WALES,18767.39,43.36,596.97,1412.04,161.94,104.65,12.75,35436.21,610.70,785954.56,243.16,0.02,1836.52,2501.41,210.89,21.22,22.54

### Extra info

In [4]:
drug_seizure_2019_DF['Component'].unique()

array(['Office of Field Operations', 'U.S. Border Patrol'], dtype=object)

In [5]:
drug_seizure_2019_DF['Region'].unique()

array(['Coastal/Interior', 'Northern Border', 'Southwest Border'],
      dtype=object)

### 2019: Northern Border

In [23]:
drug_seizure_NorthernBorder_2019 = drug_seizure_2019_DF[drug_seizure_2019_DF['Region'].isin(['Northern Border'])]
drug_seizure_NorthernBorder_2019

,FY,Month (abbv),Component,Region,Land Filter,Area of Responsibility,Drug Type,Count of Event,Sum Qty (lbs)
84,2019,APR,Office of Field Operations,Northern Border,Land Only,BOSTON FIELD OFFICE,Marijuana,21,1.175262
85,2019,APR,Office of Field Operations,Northern Border,Land Only,BOSTON FIELD OFFICE,Other Drugs**,6,0.303180
86,2019,APR,Office of Field Operations,Northern Border,Land Only,BUFFALO FIELD OFFICE,Cocaine,4,0.038206
87,2019,APR,Office of Field Operations,Northern Border,Land Only,BUFFALO FIELD OFFICE,Ecstasy,1,0.006614
88,2019,APR,Office of Field Operations,Northern Border,Land Only,BUFFALO FIELD OFFICE,Heroin,4,0.061729
...,...,...,...,...,...,...,...,...,...
10045,2022,SEP,U.S. Border Patrol,Northern Border,Land Only,HAVRE SECTOR,Methamphetamine,2,1.952600
10046,2022,SEP,U.S. Border Patrol,Northern Border,Land Only,HOULTON SECTOR,Marijuana,6,60.243300
10047,2022,SEP,U.S. Border Patrol,Northern Border,Land Only,HOULTON SECTOR,Methamphetamine,1,0.031700
10048,2022,SEP,U.S. Border Patrol,Northern Border,Land Only,SWANTON SECTOR,Cocaine,1,0.013400
10049,2022,SEP,U.S. Border Patrol,Northern Border,Land Only,SWANTON SECTOR,Marijuana,3,2.616400

### 2019: Southwest Border

In [24]:
drug_seizure_SouthwestBorder_2019 = drug_seizure_2019_DF[drug_seizure_2019_DF['Region'].isin(['Southwest Border'])]
drug_seizure_SouthwestBorder_2019

,FY,Month (abbv),Component,Region,Land Filter,Area of Responsibility,Drug Type,Count of Event,Sum Qty (lbs)
113,2019,APR,Office of Field Operations,Southwest Border,Land Only,EL PASO FIELD OFFICE,Cocaine,7,116.780403
114,2019,APR,Office of Field Operations,Southwest Border,Land Only,EL PASO FIELD OFFICE,Heroin,1,23.545370
115,2019,APR,Office of Field Operations,Southwest Border,Land Only,EL PASO FIELD OFFICE,Marijuana,36,3100.874688
116,2019,APR,Office of Field Operations,Southwest Border,Land Only,EL PASO FIELD OFFICE,Methamphetamine,6,48.933319
117,2019,APR,Office of Field Operations,Southwest Border,Land Only,EL PASO FIELD OFFICE,Other Drugs**,3,4.828807
...,...,...,...,...,...,...,...,...,...
10087,2022,SEP,U.S. Border Patrol,Southwest Border,Land Only,TUCSON SECTOR,Other Drugs**,2,0.005000
10088,2022,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Fentanyl,2,77.321300
10089,2022,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Marijuana,5,1.339200
10090,2022,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Methamphetamine,6,5.421600
10091,2022,SEP,U.S. Border Patrol,Southwest Border,Land Only,YUMA SECTOR,Other Drugs**,1,0.000100

### 2019: Coastal/Interior

In [26]:
drug_seizure_CoastalInterior_2019 = drug_seizure_2019_DF[drug_seizure_2019_DF['Region'].isin(['Coastal/Interior'])]
drug_seizure_CoastalInterior_2019

,FY,Month (abbv),Component,Region,Land Filter,Area of Responsibility,Drug Type,Count of Event,Sum Qty (lbs)
0,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Ecstasy,3,8.379947
1,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Khat (Catha Edulis),4,1394.423807
2,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Marijuana,5,0.089397
3,2019,APR,Office of Field Operations,Coastal/Interior,Other,ATLANTA FIELD OFFICE,Other Drugs**,8,42.663196
4,2019,APR,Office of Field Operations,Coastal/Interior,Other,BALTIMORE FIELD OFFICE,Cocaine,3,8.542913
...,...,...,...,...,...,...,...,...,...
10027,2022,SEP,U.S. Border Patrol,Coastal/Interior,Other,MIAMI SECTOR,Cocaine,1,2.321900
10028,2022,SEP,U.S. Border Patrol,Coastal/Interior,Other,MIAMI SECTOR,Marijuana,3,138.448800
10029,2022,SEP,U.S. Border Patrol,Coastal/Interior,Other,NEW ORLEANS SECTOR,Marijuana,2,0.154400
10030,2022,SEP,U.S. Border Patrol,Coastal/Interior,Other,NEW ORLEANS SECTOR,Methamphetamine,1,0.001100
10031,2022,SEP,U.S. Border Patrol,Coastal/Interior,Other,RAMEY SECTOR,Cocaine,1,23.461200

In [28]:
drug_seizure_2019_DF.columns

Index(['FY', 'Month (abbv)', 'Component', 'Region', 'Land Filter',
       'Area of Responsibility', 'Drug Type', 'Count of Event',
       'Sum Qty (lbs)'],
      dtype='object')

### Desglose 2019:

In [29]:
drug_seizure_2019_DF.groupby(['Area of Responsibility','Component','Land Filter','FY','Drug Type'])[['Count of Event','Sum Qty (lbs)']].sum().sort_values(by='Count of Event', ascending = False)

                                                                                  Count of Event  \
Area of Responsibility Component                  Land Filter FY   Drug Type
NEW YORK FIELD OFFICE  Office of Field Operations Other       2021 Other Drugs**           16532
                                                              2022 Other Drugs**           13560
CHICAGO FIELD OFFICE   Office of Field Operations Other       2021 Other Drugs**           10474
MIAMI FIELD OFFICE     Office of Field Operations Other       2021 Other Drugs**            9320
CHICAGO FIELD OFFICE   Office of Field Operations Other       2020 Other Drugs**            8189
...                                                                                          ...
BUFFALO FIELD OFFICE   Office of Field Operations Other       2020 Heroin                      1
SEATTLE FIELD OFFICE   Office of Field Operations Land Only   2020 Heroin                      1
RAMEY SECTOR           U.S. Border Patrol         Other       2019 Marijuana                   1
TAMPA FIELD OFFICE     Office of Field Operations Other       2021 Ketamine                    1
PORTLAND FIELD OFFICE  Office of Field Operations Other       2019 Heroin                      1

                                                                                  Sum Qty (lbs)
Area of Responsibility Component                  Land Filter FY   Drug Type
NEW YORK FIELD OFFICE  Office of Field Operations Other       2021 Other Drugs**   10957.731621
                                                              2022 Other Drugs**   15068.693757
CHICAGO FIELD OFFICE   Office of Field Operations Other       2021 Other Drugs**   16054.686709
MIAMI FIELD OFFICE     Office of Field Operations Other       2021 Other Drugs**   10517.399215
CHICAGO FIELD OFFICE   Office of Field Operations Other       2020 Other Drugs**   10302.008378
...                                                                                         ...
BUFFALO FIELD OFFICE   Office of Field Operations Other       2020 Heroin              0.276460
SEATTLE FIELD OFFICE   Office of Field Operations Land Only   2020 Heroin              0.014793
RAMEY SECTOR           U.S. Border Patrol         Other       2019 Marijuana         256.000000
TAMPA FIELD OFFICE     Office of Field Operations Other       2021 Ketamine            2.910102
PORTLAND FIELD OFFICE  Office of Field Operations Other       2019 Heroin              2.169349

[1421 rows x 2 columns]

Quitamos: Component y Land Region

In [31]:
drug_seizure_2019_DF.groupby(['Area of Responsibility','FY','Drug Type'])[['Count of Event','Sum Qty (lbs)']].sum().sort_values(by='Count of Event', ascending = False)

                                             Count of Event  Sum Qty (lbs)
Area of Responsibility FY   Drug Type
NEW YORK FIELD OFFICE  2021 Other Drugs**             16532   10957.731621
                       2022 Other Drugs**             13560   15068.693757
CHICAGO FIELD OFFICE   2021 Other Drugs**             10474   16054.686709
MIAMI FIELD OFFICE     2021 Other Drugs**              9320   10517.399215
CHICAGO FIELD OFFICE   2020 Other Drugs**              8189   10302.008378
...                                                     ...            ...
TAMPA FIELD OFFICE     2021 Ketamine                      1       2.910102
BLAINE SECTOR          2021 Methamphetamine               1     341.981000
HAVRE SECTOR           2021 Fentanyl                      1       0.377000
                       2020 Other Drugs**                 1       0.005500
EL PASO FIELD OFFICE   2020 Ketamine                      1       1.918683

[1222 rows x 2 columns]

Quitamos Drug Type, mantenemos Fiscal Year:

In [1]:
drug_seizure_2019_DF.groupby(['Area of Responsibility','FY'])[['Count of Event','Sum Qty (lbs)']].sum().sort_values(by='Count of Event', ascending = False)

NameError: name 'drug_seizure_2019_DF' is not defined

Quitamos Fiscal Year, mantenemos Drug Type:

In [33]:
drug_seizure_2019_DF.groupby(['Area of Responsibility','Drug Type'])[['Count of Event','Sum Qty (lbs)']].sum().sort_values(by='Count of Event', ascending = False)

                                               Count of Event  Sum Qty (lbs)
Area of Responsibility    Drug Type
NEW YORK FIELD OFFICE     Other Drugs**                 43617   48528.663790
CHICAGO FIELD OFFICE      Other Drugs**                 29795   41041.649233
MIAMI FIELD OFFICE        Other Drugs**                 23192   32874.793722
NEW YORK FIELD OFFICE     Ecstasy                       10511    2995.338389
SAN DIEGO FIELD OFFICE    Methamphetamine                7475  371731.647180
...                                                       ...            ...
TUCSON FIELD OFFICE       Khat (Catha Edulis)               1       9.634201
PRECLEARANCE FIELD OFFICE Fentanyl                          1       0.266759
DEL RIO SECTOR            Fentanyl                          1       0.000400
HAVRE SECTOR              Cocaine                           1       0.500000
TAMPA FIELD OFFICE        Fentanyl                          1       0.335103

[337 rows x 2 columns]

In [36]:
drug_seizure_2019_DF['Area of Responsibility'].unique()

array(['ATLANTA FIELD OFFICE', 'BALTIMORE FIELD OFFICE',
       'CHICAGO FIELD OFFICE', 'HOUSTON FIELD OFFICE',
       'LOS ANGELES FIELD OFFICE', 'MIAMI FIELD OFFICE',
       'NEW ORLEANS FIELD OFFICE', 'NEW YORK FIELD OFFICE',
       'PRECLEARANCE FIELD OFFICE', 'SAN FRANCISCO FIELD OFFICE',
       'SAN JUAN FIELD OFFICE', 'TAMPA FIELD OFFICE',
       'BOSTON FIELD OFFICE', 'BUFFALO FIELD OFFICE',
       'DETROIT FIELD OFFICE', 'SEATTLE FIELD OFFICE',
       'PORTLAND FIELD OFFICE', 'EL PASO FIELD OFFICE',
       'LAREDO FIELD OFFICE', 'SAN DIEGO FIELD OFFICE',
       'TUCSON FIELD OFFICE', 'MIAMI SECTOR', 'BLAINE SECTOR',
       'BUFFALO SECTOR', 'DETROIT SECTOR', 'HAVRE SECTOR',
       'HOULTON SECTOR', 'SPOKANE SECTOR', 'SWANTON SECTOR',
       'BIG BEND SECTOR', 'DEL RIO SECTOR', 'EL CENTRO SECTOR',
       'EL PASO SECTOR', 'LAREDO SECTOR', 'RIO GRANDE VALLEY SECTOR',
       'SAN DIEGO SECTOR', 'TUCSON SECTOR', 'YUMA SECTOR',
       'NEW ORLEANS SECTOR', 'RAMEY SECTOR', 'GRAND FORKS SECTOR'],
      dtype=object)

- 0: -- Charleston
- 1: PORTLAND FIELD OFFICE
- 2: HOUSTON FIELD OFFICE | Houston Air And Marine Branch: Houston (TX)
- 3: LOS ANGELES FIELD OFFICE | AMOC Air And Marine Operations Center: Los Angeles (CA)
- 4: -- Honolulu
- 5: 
- 6: NEW YORK FIELD OFFICE
- 7: 
- 8: NEW ORLEANS FIELD OFFICE/ NEW ORLEANS SECTOR | New Orleans Air And Marine Branch: Nueva Orleans (LO)
- 9: MIAMI FIELD OFFICE/MIAMI SECTOR | Miami Air And Marine Branch: Miami & Fort Lauderdale (FL)
- 10: DETROIT FIELD OFFICE/DETROIT SECTOR
- 11: # Algunos campos de 25 pueden pasar aqui (Vancouver)
- 12: - | Manassas Air Branch: Washington DC, Norfolk (VI)
- 13: SAN FRANCISCO FIELD OFFICE
- 14: TAMPA FIELD OFFICE
- 15: SAN JUAN FIELD OFFICE | Caribbean Air And Marine Branch: Puerto Rico | RAMEY
- 16: - Mobile (Alabama)
- 17: CHICAGO FIELD OFFICE | Great Lakes Air And Marine Branch: Chicago (IL), Kenosha (WI)
- 18: # SWANTON SECTOR
- 19: NASOC - Corpus Christi: Corpus Christi (TX)
- 20: # GRAND FORKS SECTOR
- 21: BALTIMORE FIELD OFFICE
- 22: - | Jacksonville Air And Marine Branch + NASOC - Jacksonville: Jacksonville (FL)
- 23: BOSTON FIELD OFFICE
- 24: SAN DIEGO FIELD OFFICE/SAN DIEGO SECTOR | San Diego Air And Marine Branch: San Diego (CA)
- 25: SEATTLE FIELD OFFICE | Bellingham Air Branch: Seattle, frontera con Canada | BLAINE SECTOR
- 26: 
- 27: 
- 28: ATLANTA FIELD OFFICE
- 29: BUFFALO FIELD OFFICE/BUFFALO SECTOR | PRECLEARANCE FIELD OFFICE
- 30: Wilmington (NC)

## 2. Exploracion de datos
Con yprofiling

In [ ]:
# 2. Exploracion de los datos

Extensión de la tabla a los años anteriores.
- Normalizar columna FY-Month: (%yyyy-MM)
- Union entre las tablas con misma estructura

In [ ]:
# 3. Visualizacion
# 4. Visualizacion en mapa

# Drug Seizure in the UK
To mars 2022

In [94]:
import xlrd
# from curating_functions import remove_note

In [95]:
xlrd.__version__

'2.0.1'

In [96]:
# Extraer datos de las tablas: Area_Table_1 - Area_Table_6
ficheros_uk = '../home_uk/seizures-drugs-mar2022-tables-310322.xls'
uk_drug_seizure_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_1', # Lista con Area_Table_i donde i=1:6
                                   header=2,
                                   usecols="A:Q",
                                   skiprows=[6,12,17,23,28,35,38,44,50,51,56,57],
                                   engine='xlrd'
                                   )

In [127]:
# Count of Event per drug type (2019)
ficheros_uk = '../home_uk/seizures-drugs-mar2019-hosb3119-tables.xls'
uk_drug_seizure_2019_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_3',
                                   header=3,
                                   usecols="A:Y",
                                   skiprows=[8,9,15,16,21,22,28,29,34,35,42,43,46,47,53,54,60,61,62,63,68,69,71,73,75,77,78,79,80,81,82,83,84,85,86],
                                   engine='xlrd'
                                   )

In [128]:
uk_drug_seizure_2019_df.rename({'Unnamed: 0':'Police force region or authority'},inplace=True)

In [129]:
# Count of Event per drug type (2020)
ficheros_uk = '../home_uk/seizures-drugs-mar2020-hosb3920-tables.xls'
uk_drug_seizure_2020_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_3',
                                   header=3,
                                   usecols="A:Y",
                                   skiprows=[4,5,9,10,16,17,22,23,29,30,35,36,43,44,47,48,54,55,61,62,63,64,69,70,72,74,76,78,79,80,81,82,83,84,86,87,88],
                                   engine='xlrd'
                                   )

In [130]:
# Count of Event per drug type (2021)
ficheros_uk = '../home_uk/seizures-drugs-mar2021-tables-030222.xls'
uk_drug_seizure_2021_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_3',
                                   header=4,
                                   usecols="A:Y",
                                   skiprows=[5,9,10,16,17,22,23,29,30,35,36,43,44,47,48,54,55,61,62,63,64,69,70,72,74,76,78,79,80,81,82,83,84,86,87,88,90,91],
                                   engine='xlrd'
                                   )

In [131]:
# Count of Event per drug type (2022)
ficheros_uk = '../home_uk/seizures-drugs-mar2022-tables-310322.xls'
uk_drug_seizure_2022_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_3',
                                   header=3,
                                   usecols="A:Y",
                                   skiprows=[7,13,18,24,29,36,39,45,51,52,57],
                                   engine='xlrd'
                                   )

uk_drug_seizure_2022_df.rename({'Unnamed: 0':'Police force region or authority'},inplace=True)

In [137]:
# Count of Event per drug type (2023)
ficheros_uk = '../home_uk/seizures-drugs-mar2023-tables-04032024.xls'
uk_drug_seizure_2023_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_3',
                                   header=3,
                                   usecols="A:Y",
                                   skiprows=[7,13,18,24,29,36,39,45,51,52,57],
                                   engine='xlrd'
                                   )

In [138]:
# Count of Event per drug type (2024)
ficheros_uk = '../home_uk/seizures-drugs-mar2024-tables-16012025.xls'
uk_drug_seizure_2024_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_3',
                                   header=3,
                                   usecols="A:Y",
                                   skiprows=[7,13,18,24,29,36,39,45,51,52,57],
                                   engine='xlrd'
                                   )

Agrupar dataframes uk_drug_seizure de los distintos años y generar un long_dataframe

In [140]:
### AQUI!!!

[Table 1] Number of seizures of controlled drugs by seizing authority and year, years ending March 2007 to 2022

In [134]:
import re

def remove_note(text):
    return re.sub(r"\[note \d+\]", "", text)

In [10]:
uk_drug_seizure_df['Police force region or authority'] = uk_drug_seizure_df['Police force region or authority'].apply(remove_note)

 - Extender datos para Area_Table 2:6
 - Normalizar entrada de Hojas de excel.
 - ¿Se podrá hacer la extensión en columnas por cada nueva hoja excel que se añada?
 - Añadir nueva columna con la region asociada

[Table 2] Area Table 2: Drug seizures per million population by police force area and year, years ending March 2007 to 2022 [note 17]

In [12]:
ficheros_uk = '../home_uk/seizures-drugs-mar2022-tables-310322.xls'
uk_drug_seizure_ppm_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_2',
                                   header=2,
                                   usecols="A:Q",
                                   skiprows=[6,12,17,23,28,35,38,44,50,51,56,57],
                                   engine='xlrd'
                                   )

In [13]:
uk_drug_seizure_ppm_df['Police force region or authority'] = uk_drug_seizure_ppm_df['Police force region or authority'].apply(remove_note)

Tabla 3:  Number of drug seizures by drug class, type and seizing authority, years ending March 2022\
Tabla 4:  Drug seizures per million population by drug class, type and police force area, year ending March 2022 [note 17]

Tabla 5: Area Table 5: Quantity of drugs seized by drug class, type and seizing authority, year ending March 2022 [notes 9, 10]\
Estandarizar la unidad de masa (kg o lbs)

In [141]:
ficheros_uk = '../home_uk/seizures-drugs-mar2019-hosb3119-tables.xls'
uk_drug_seizure_kg_2019_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_5',
                                   header=3,
                                   usecols="A:R",
                                   skiprows=[4,5,9,10,16,17,22,23,29,30,35,36,43,44,47,48,54,55,61,62,63,64,69,70,72,74,76,78,79,80,81,82,83,84,85,86,87,88],
                                   engine='xlrd'
                                   )

In [143]:
ficheros_uk = '../home_uk/seizures-drugs-mar2020-hosb3920-tables.xls'
uk_drug_seizure_kg_2020_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_5',
                                   header=3,
                                   usecols="A:R",
                                   skiprows=[4,5,6,10,11,17,18,23,24,30,31,36,37,44,45,48,49,55,56,62,63,64,65,70,71,73,75,77,79,80,81,82,83,84,86,87,88],
                                   engine='xlrd'
                                   )

In [144]:
ficheros_uk = '../home_uk/seizures-drugs-mar2021-tables-030222.xls'
uk_drug_seizure_kg_2021_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_5',
                                   header=3,
                                   usecols="A:R",
                                   skiprows=[4,5,9,10,16,17,22,23,29,30,35,36,43,44,47,48,54,55,61,62,63,64,69,70,72,74,76,78,79,80,81,82,83,84,85,86,87,89,90],
                                   engine='xlrd'
                                   )

In [145]:
ficheros_uk = '../home_uk/seizures-drugs-mar2022-tables-310322.xls'
uk_drug_seizure_kg_2022_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_5',
                                   header=3,
                                   usecols="A:R",
                                   skiprows=[8,14,19,25,30,37,40,46,52,53,58],
                                   engine='xlrd'
                                   )

In [146]:
ficheros_uk = '../home_uk/seizures-drugs-mar2023-tables-04032024.xls'
uk_drug_seizure_kg_2023_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_5',
                                   header=3,
                                   usecols="A:R",
                                   skiprows=[4,8,14,19,25,30,37,40,46,52,53,58],
                                   engine='xlrd'
                                   )

In [147]:
ficheros_uk = '../home_uk/seizures-drugs-mar2024-tables-16012025.xls'
uk_drug_seizure_kg_2024_df = pd.read_excel(ficheros_uk,
                                   sheet_name ='Area_Table_5',
                                   header=3,
                                   usecols="A:R",
                                   skiprows=[4,8,14,19,25,30,37,40,46,52,53,58],
                                   engine='xlrd'
                                   )

Agrupar los dataframes anteriores (uk drug seizure kg per year)

In [148]:
#### AQUI!!!

Excepto para "Cannabis Plants" [plant], el resto de unidades son kg.

Table 6: Proportion of drug seizures by region or authority, years ending March 2007 to 2022

In [16]:
# Guardar en .csv:
uk_drug_seizure_df.to_csv('../home_uk/uk_drug_seizure_df.csv', index=False)
uk_drug_seizure_ppm_df.to_csv('../home_uk/uk_drug_seizure_ppm_df.csv', index=False)
uk_drug_seizure_kg_df.to_csv('../home_uk/uk_drug_seizure_kg_df.csv', index=False)

# Drug Seizure in EU